// lib/productBrands.ts

export const PRODUCT_BRANDS: Record<string, any> = {
  webman: {
    bg: "#0A0A0A",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: "M",
    mark: "square-letter",
    logoColor: "#10B981",
    nameParts: ["Web", "man"],
    namePart1Color: "#ffffff",
    namePart2Color: "#D97706",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "PROUDLY NIGERIAN. GLOBALLY STANDARD.",
    tagColor: "#10B981",
    headingLines: [
      { text: "Your business" },
      { text: "deserves to be" },
      { text: "found online.", accent: true },
    ],
    accentColor: "#D97706",
    description: "Deploy your business website in under 5 minutes. No servers. No DevOps. No stress.",
    orbitWords: ["DEPLOY", "DOMAIN", "GO LIVE"],
    ctaText: "START FREE — NO CARD NEEDED",
    ctaDomain: "webman.justservices.pro",
    ctaBg: "#D97706",
    ctaTextColor: "#1a1200",
    cornerColor: "#D97706",
  },
  certtrack: {
    bg: "#0B1E3D",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.6)",
    logoLetter: "✓",
    mark: "shield-check",
    logoColor: "#0B1E3D",
    logoTextColor: "#E9C46A",
    nameParts: ["CertTrack", ""],
    namePart1Color: "#ffffff",
    namePart2Color: "#ffffff",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "FOR TRAINING PROVIDERS AND ORGANIZATIONS",
    tagColor: "#E9C46A",
    headingLines: [
      { text: "Run your cohorts." },
      { text: "Issue credentials" },
      { text: "no one can fake.", accent: true },
    ],
    accentColor: "#E9C46A",
    description: "Enrollment, attendance, and QR-verified certificates — one dashboard for training providers, one portal for every student.",
    medal: true,
    ctaText: "Start free for 30 days · No card required",
    ctaDomain: "certtrack.justservices.pro",
    ctaBg: "#E9C46A",
    ctaTextColor: "#0B1E3D",
    cornerColor: "#E9C46A",
  },
  prodoc: {
    bg: "#04140D",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: "✓",
    mark: "document-check",
    logoColor: "#059669",
    logoTextColor: "#ffffff",
    nameParts: ["Pro", "Doc"],
    namePart1Color: "#ffffff",
    namePart2Color: "#D97706",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "BUILT FOR NIGERIAN BUSINESSES",
    tagColor: "#10B981",
    headingLines: [
      { text: "Generate invoice", accent: true },
      { text: "in under 3 minutes" },
    ],
    accentColor: "#D97706",
    description: "10 professionally formatted, Nigeria-compliant business documents. Fill a form, pay once, download instantly — no lawyer needed.",
    orbitWords: ["NIGERIA-COMPLIANT", "INSTANT", "SECURE"],
    ctaText: "Start for free",
    ctaDomain: "prodoc.justservices.pro",
    ctaBg: "#D97706",
    ctaTextColor: "#1a1200",
    cornerColor: "#D97706",
  },
  appaholic: {
    bg: "#F3EEE3",
    textColor: "#111111",
    subTextColor: "#4b4438",
    logoLetter: "A",
    logoColor: "#111111",
    logoTextColor: "#D97706",
    nameParts: ["App", "Aholic"],
    namePart1Color: "#111111",
    namePart2Color: "#111111",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "PRODUCTIVITY APPS FOR WORK AND BUSINESS",
    tagColor: "#B4740E",
    headingLines: [
      { text: "The toolshed", accent: true },
      { text: "for Nigerian" },
      { text: "businesses." },
    ],
    accentColor: "#B4740E",
    description: "A catalogued stock of practical Web, Desktop and Mobile apps — built for the way small businesses and freelancers actually work here.",
    orbitWords: ["WEB", "DESKTOP", "MOBILE"],
    ctaText: "BROWSE THE CATALOGUE",
    ctaDomain: "appaholic.justservices.pro",
    ctaBg: "#161616",
    ctaTextColor: "#E9C46A",
    cornerColor: "#B4740E",
  },
  processa: {
    bg: "#0A0E14",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: "P",
    mark: "hex-p",
    logoColor: "#12B8B3",
    logoTextColor: "#ffffff",
    nameParts: ["Pro", "cessa"],
    namePart1Color: "#ffffff",
    namePart2Color: "#22D3C7",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "ALL-IN-ONE FILE TOOLKIT",
    tagColor: "#22D3C7",
    headingLines: [
      { text: "Process anything." },
      { text: "Instantly.", accent: true },
    ],
    accentColor: "#7C6CF0",
    description: "Convert files, edit PDFs, resize images, format documents, generate QR codes — 49 tools, one platform, no sign-up required.",
    orbitWords: ["PROCESS", "CONVERT", "INSTANT"],
    ctaText: "Start free — 2 uses/tool/day",
    ctaDomain: "processa.justservices.pro",
    ctaBg: "#22D3C7",
    ctaTextColor: "#00201d",
    cornerColor: "#22D3C7",
  },
  justbuys: {
    bg: "#F5FBF6",
    textColor: "#0d1f13",
    subTextColor: "#516657",
    logoLetter: "JB",
    logoColor: "#059669",
    nameParts: ["Just", "Buys"],
    namePart1Color: "#0d1f13",
    namePart2Color: "#059669",
    domainLabel: "JUSTBUYS.DEALS",
    tagLabel: "ONE MARKETPLACE, FOR YOUR WORK NEEDM",
    tagColor: "#059669",
    headingLines: [
      { text: "Whatever your Work needs," },
      { text: "from gadgets to digital items to workspaces.", accent: true },
    ],
    accentColor: "#059669",
    description: "Gadgets, digital products, verified short lets, courses and more — search one marketplace instead of ten different pages.",
    orbitWords: ["GADGETS", "DIGITAL", "PROPERTY"],
    ctaText: "GOOD DEALS",
    ctaDomain: "justbuys.deals",
    ctaBg: "#064E3B",
    ctaTextColor: "#ffffff",
    cornerColor: "#059669",
  },
  orgnexus: {
    bg: "#0B1220",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: "N",
    mark: "network-nexus",
    logoColor: "#F0653C",
    logoTextColor: "#ffffff",
    nameParts: ["Org", "Nexus"],
    namePart1Color: "#ffffff",
    namePart2Color: "#F0653C",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "YOUR ORG. YOUR COMMUNITY. ONE PLATFORM.",
    tagColor: "#F0653C",
    headingLines: [
      { text: "Your community," },
      { text: "under your brand,", accent: true },
      { text: "not ours." },
    ],
    accentColor: "#F0653C",
    description: "Branded community platform for churches, alumni networks, gyms and nonprofits — members sign up, post, and message, all under your own name.",
    orbitWords: ["FEED", "MESSAGE", "MODERATE"],
    ctaText: "Start free — no card required",
    ctaDomain: "orgnexus.justservices.pro",
    ctaBg: "#F0653C",
    ctaTextColor: "#ffffff",
    cornerColor: "#F0653C",
  },
  devtrac: {
    bg: "#0A0F0C",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: "◈",
    mark: "map-pin",
    logoColor: "#F2A93B",
    logoTextColor: "#ffffff",
    nameParts: ["Dev", "Trac"],
    namePart1Color: "#ffffff",
    namePart2Color: "#F2A93B",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "YOUR ONE MOST IMPORTANT ASSET, SAFEGUARD YOUR PHONE",
    tagColor: "#F2A93B",
    headingLines: [
      { text: "Your Phone: Your Asset - Find it. Lock it." },
      { text: "Get it back.", accent: true },
    ],
    accentColor: "#F2A93B",
    description: "Real-time tracking, remote lock and wipe, and a one-click police report — turning a stolen device into a setback, not a loss.",
    orbitWords: ["TRACK", "LOCK", "RECOVER"],
    ctaText: "Start tracking free",
    ctaDomain: "devtrac.justservices.pro",
    ctaBg: "#F2A93B",
    ctaTextColor: "#1a1200",
    cornerColor: "#F2A93B",
  },
  leadflo: {
    bg: "#170611",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: "L",
    mark: "funnel-bolt",
    logoColor: "#EC4899",
    logoTextColor: "#ffffff",
    nameParts: ["Lead", "flo"],
    namePart1Color: "#ffffff",
    namePart2Color: "#EC4899",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "LEAD CAPTURE & FOLLOW-UP FOR SALES TEAMS",
    tagColor: "#EC4899",
    headingLines: [
      { text: "Every enquiry," },
      { text: "followed up,", accent: true },
      { text: "every time." },
    ],
    accentColor: "#EC4899",
    description: "Capture leads from your website, WhatsApp and ads into one pipeline, score them automatically, and let scheduled follow-ups chase them down before they go cold.",
    orbitWords: ["CAPTURE", "SCORE", "FOLLOW UP"],
    ctaText: "Start free — no card required",
    ctaDomain: "leadflo.justservices.pro",
    ctaBg: "#EC4899",
    ctaTextColor: "#ffffff",
    cornerColor: "#EC4899",
  },
  fixit: {
    bg: "#0A0A0A",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: "◇",
    logoColor: "#EA580C",
    nameParts: ["Fix", "It Abuja"],
    namePart1Color: "#EA580C",
    namePart2Color: "#ffffff",
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: "AVOID WORK DOWNTIMES, TECHNICIANS ON STANDBY ACROSS ABUJA",
    tagColor: "#10B981",
    headingLines: [
      { text: "When it breaks" },
      { text: "down in Abuja," },
      { text: "we show up.", accent: true },
    ],
    accentColor: "#EA580C",
    description: "FixIt Abuja sends vetted technicians to your home or office for generator, printer, laptop, AC, inverter and CCTV repairs.",
    orbitWords: ["FAST", "VETTED", "FAIR PRICE"],
    ctaText: "CHAT ON WHATSAPP",
    ctaDomain: "fixit.justservices.pro",
    ctaBg: "#EA580C",
    ctaTextColor: "#1a0900",
    cornerColor: "#EA580C",
  },
};

// ── Safe lookup ──────────────────────────────────────────────────────────
// PRODUCT_BRANDS above is hand-curated per product id. If a product exists in
// PRODUCTS_DATA (lib/constants.ts) but its id isn't in this file yet — e.g. a
// new product was added here without an entry above, or an id was renamed —
// this generates a reasonable brand config on the fly from the product's own
// fields instead of the page crashing with "Cannot read properties of undefined".
function splitName(name: string): [string, string] {
  const idx = (name || "").indexOf(" ");
  if (idx === -1) return [name || "", ""];
  return [name.slice(0, idx), name.slice(idx)];
}

export function getProductBrand(p: any): any {
  const explicit = p?.id ? PRODUCT_BRANDS[p.id] : undefined;
  if (explicit) return explicit;
  const color = p?.color || "#1A4A8A";
  return {
    bg: "#0B1220",
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.55)",
    logoLetter: (p?.name || "?").trim().charAt(0).toUpperCase(),
    logoColor: color,
    logoTextColor: "#ffffff",
    nameParts: splitName(p?.name || ""),
    namePart1Color: "#ffffff",
    namePart2Color: color,
    domainLabel: "JUSTSERVICESPRO",
    tagLabel: (p?.badge || p?.tagline || "").toUpperCase(),
    tagColor: color,
    headingLines: [{ text: p?.tagline || p?.name || "", accent: true }],
    accentColor: color,
    description: p?.description || "",
    orbitWords: [p?.badge || "PLATFORM"],
    ctaText: p?.cta || "Learn more",
    ctaDomain: (p?.url || "").replace(/^https?:\/\//, "").replace(/\/$/, ""),
    ctaBg: color,
    ctaTextColor: "#ffffff",
    cornerColor: color,
  };
}
